### ISSUE TITLE
startScan() doesn't open native camera

### ISSUE THREAD

**Issue by eryzerz** [DutchConcepts/capacitor-barcode-scanner#1]
**Describe the bug**
I installed this plugin on Ionic 5 Angular iOS project. Whenever I run startScan method, it doesn't trigger native camera and no error message. The only thing I can see in log is this 
```
⚡️  To Native ->  BarcodeScanner hideBackground 7747052
⚡️  To Native ->  BarcodeScanner startScan 7747053
```

**To Reproduce**

1. Follow install plugin instruction at readme 
2. Import Plugins 
`import { Plugins } from '@capacitor/core';`

3. Put prepare on ionViewWillEnter()
4. Create wrapper function to call startScan method. 
```
async openBarcodeScanner() {
    const { BarcodeScanner } = Plugins;
    
    BarcodeScanner.hideBackground();
    try {
      const barcodeData = await BarcodeScanner.startScan()
        console.log('Barcode data', barcodeData);
        if(barcodeData.hasContent) {
          this.checkBarcode(barcodeData.content);
        }
    } catch (err) {
      console.log('Scan barcode error', err);
    }
  } 

```
5. Edit info.plist, set camera usage description
6. Ionic build, sync, then open ios

**Expected behavior**
When startScan method get called, screen should immediately navigate to native camera.

**Smartphone (please complete the following information):**

- Device: iPhone 6
- OS: iOS 12.4.9

**Comment by tafelnl** [comment]
You might have forgotten to request the camera permission. See https://github.com/DutchConcepts/capacitor-barcode-scanner#permissions. You can use Capacitor's official permission plugin: https://capacitorjs.com/docs/apis/permissions

I am planning on implementing this into this library for convenience. But as of now, you have to do this manually.

**Comment by bash88** [comment]
Hi @tafelnl,

Running into the same problem here. Capacitor's official permission plugin (the one you linked to) only allows for querying the status of permissions, not requesting them. At least for as far as I can see.

Do you maybe have an example or suggestion for requesting permissions?

Regards,
Bas

**Comment by tafelnl** [comment]
Hm, I see now. Hold on tight as I will release a solution for this in a couple of days. In the meantime you could request permission with this plugin for example: https://www.npmjs.com/package/capacitor-plugin-permissions

**Comment by bash88** [comment]
https://www.npmjs.com/package/capacitor-plugin-permissions and also https://github.com/jayordway/capacitor-permissions both have issues when building in Xcode because they don't account for the new 'limited' status Apple introduced for permissions.

I tried to fix it in the swift files but I'm far from a native iOS expert so couldn't get it to work.

Holding on really tight for the release of your solution!

**Comment by tafelnl** [comment]
Just an update: I am working on it as we speak. ETA: 2nd of november

**Comment by tafelnl** [comment]
@eryzerz @bash88 @herefisyfish

I am delighted to announce that I just released a version with permission utils added.

You can install it by running:

```
npm install git+https://github.com/DutchConcepts/capacitor-barcode-scanner.git#v1.0.0-alpha.5
npx cap sync
```

Documentation can be found here: https://github.com/DutchConcepts/capacitor-barcode-scanner/tree/feat/permissions#permissions

I am inviting you guys to test it out and share some feedback

**Comment by herefishyfish** [comment]
Thanks for the hard work. Will let you know how it goes 👍

**Comment by bash88** [comment]
Awesome! Going to try it right away

**Comment by bash88** [comment]
Pretty sure I'm doing everything right, but getting this error in the Xcode console:

⚡️  To Native ->  BarcodeScanner checkPermission 15561934
⚡️  Error: Plugin BarcodeScanner does not respond to method call "checkPermission" using selector "checkPermission:".
⚡️  Ensure plugin method exists, uses @objc in its declaration, and arguments match selector without callbacks in CAP_PLUGIN_METHOD.
⚡️  Learn more: https://capacitorjs.com/docs/plugins/ios/#defining-methods

**Comment by tafelnl** [comment]
Was able to reproduce your issue @bash88. It looks like something goes wrong when running `cap sync` after updating the package. A very simple fix: within Xcode do the following: `Product` > `Clean Build Folder`. And then run again. That should fix it.

**Comment by delciopolanco** [comment]
I have the same issue with IOS 14.7.1, I have tested in two different devices iPhone XR and iPhone 6 Plus.

After executing the startScan method,  doesn't open the native camera, not show errors and receive this output in the Xcode console:

![image](https://user-images.githubusercontent.com/20881846/141812232-666f1866-040f-45b8-8eca-ec390cbaaa44.png)

**Comment by laszloblum** [comment]
@delciopolanco  I have the same error.
