### ISSUE TITLE
Getting @color/colorPrimary instead of the BarcodeView

### ISSUE THREAD

**Issue by shangeeee** [DutchConcepts/capacitor-barcode-scanner#12]
After setting everything transparent in the web view, the Barcode View is not showing up but barcode scans are working properly. It is only the app primary color that is in the background. 

I edit a little the source code by bringing the Barcode View to the front instead of the WebView everything works properly but I cannot take advantage of the custom personalisation with HTML/CSS.

Ionic CLI : 6.12.3
Ionic Framework: 5.1.1
Capacitor: 2.1.1

Android: 6

Thanks

**Comment by tafelnl** [comment]
Have you tried debugging it like this: https://github.com/DutchConcepts/capacitor-barcode-scanner/issues/7#issuecomment-744441148

**Comment by shangeeee** [comment]
Yes. I tried
I upgrade my ionic version and now it is working. 
Thanks
