### ISSUE TITLE
hideBackground not working?

### ISSUE THREAD

**Issue by k3341095** [DutchConcepts/capacitor-barcode-scanner#15]
**Version**
Dev mode.......... capacitor
 Pkg quasar........ v1.15.0
 Pkg @quasar/app... v2.1.14
 Debugging......... enabled
 Running mode...... IDE (manual)

**Desktop (please complete the following information):**

- OS: windows
- Browser chrome

**Smartphone (please complete the following information):**

- Device: samsung galaxy s10
- OS:  10.0
- Browser 

**Additional context**
Hello.. Thank you for making a great program.
There are some strange things, so I ask you a question.

I am using the quasar framework.
My source is
 methods: {
    async checkPermission() {
      const { BarcodeScanner } = Plugins;
      const status = await BarcodeScanner.checkPermission({ force: true });

      if (status.granted) {
        // 권한이 부여 된 사용자
        return true;
      }

      return false;
    },
    async startScan() {
      try {
        const { BarcodeScanner } = Plugins;

        const status = await this.checkPermission();

        await BarcodeScanner.hideBackground();
        const result = await BarcodeScanner.startScan();
        if (result.hasContent) {
          alert(result.content);
        }
      } catch (error) {
        alert(error);
        console.error(error);
      }
    }

When I run the scan... nothing happens.
It seems that hideBackground is not doing anything.

However, when the barcode is scanned... the barcode is output as an alert.

It works fine, but I can't see the scan screen.

Is there any other way I can try?

**Comment by tafelnl** [comment]
Have you tried debugging it like this: #7 (comment)

**Comment by k3341095** [comment]
There was an image on my page.
I set the image to none and it works fine.
Thank you..
The zxing module seems to be slow to recognize code 128..
Trying to apply another module. mlkit

**Comment by tafelnl** [comment]
Good to hear you got it working! If you have further questions about code 128 or anything else, please open a new issue 💯
