### ISSUE TITLE
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.dutchconcepts.capacitor.barcodescanner.BarcodeScanner, unresolved supertypes: com.journeyapps.barcodescanner.BarcodeCallback

### ISSUE THREAD

**Issue by tomasyun** [DutchConcepts/capacitor-barcode-scanner#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
[e.g. v1.0.0]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tafelnl** [comment]
Could you please provide more information? If you would he able to fill out the bug template, that would help a lot

**Comment by tomasyun** [comment]
I added it step by step according to the introduction on the readme; but my native code uses the plugin added by Kotlin
![1611540541(1)](https://user-images.githubusercontent.com/13829185/105652893-633ef180-5ef5-11eb-996b-9bc38f21534d.jpg)

**Comment by tafelnl** [comment]
Can you try the following:

In Android Studio click `File` `>` `Sync Project with Gradle Files` and try to build again.

**Comment by tafelnl** [comment]
Closing this issue. If you are still experiencing this issue, please do not hesitate to ask for help again!
