### ISSUE TITLE
No podspec found for `DutchconceptsCapacitorBarcodeScanner` in `../../node_modules/@dutchconcepts/capacitor-barcode-scanner`

### ISSUE THREAD

**Issue by Jacobra93** [DutchConcepts/capacitor-barcode-scanner#5]
**Describe the bug**
When trying to install the plugin, I get an error saying there is no podspec found for the plugin.

**To Reproduce**

1. Follow installation instructions - starting with `npm install @dutchconcepts/capacitor-barcode-scanner`
2. Run npx cap sync
3. See error: 

> No podspec found for `DutchconceptsCapacitorBarcodeScanner` in `../../node_modules/@dutchconcepts/capacitor-barcode-scanner`

**Expected behavior**
When running npx cap sync we should not get this error.

**Additional context**
 I see a podspec file in capacitor-barcode-scanner, so not sure why it's not finding it. Even after adding it to Info.plist, I still get this error. I have not tried it on Android yet so do not know if the plugin works there.

**Comment by tafelnl** [comment]
Can you try installing the just released 1.0.1 version? That should fix it.

**Comment by Jacobra93** [comment]
@tafelnl 
Installing the newest version fixed it! Thanks.
