### ISSUE TITLE
It only scans QRCodes 

### ISSUE THREAD

**Issue by ahmedogela** [DutchConcepts/capacitor-barcode-scanner#6]
It only scans QRCodes in both ios and android.
Did you try to scan a barcode? and is there any settings to make it work?
It is good plugin but it can't recognize barcodes only qrcodes!

**Comment by tafelnl** [comment]
I just tested on Android and it is able to scan barcodes.

Can you provide some more information on the type of device you are using and the barcode you are trying to scan?

**Comment by ahmedogela** [comment]
Device: Iphone X
Barcode Type: I tried various products with different types of barcode printed on their labels

**Comment by ahmedogela** [comment]
I have just tried these barcodes and only accept to scan the qrcode

![Barcodes](https://user-images.githubusercontent.com/32929249/101814295-9f291d80-3b26-11eb-861f-3628170d5f93.jpg)

**Comment by tafelnl** [comment]
A lot of those should be supported. Did you test it in Android as well? I will dive into this tomorrow.

**Comment by ahmedogela** [comment]
Yes I tested on HTC desire 626s and it is same as ios, only qrcode.

**Comment by tafelnl** [comment]
Will get back to you tomorrow. If you are able to deliver a working reproduction example, that would help enormously.

**Comment by tafelnl** [comment]
I think I know why it would not scan those barcodes on iOS. But on Android it should work. So if you could deliver an example for Android that would be great.

**Comment by ahmedogela** [comment]
Sure, I will make an example for android

**Comment by ahmedogela** [comment]
While I make an example for android, I figure out that it works :) but it takes some noticeable time to recognize the barcode, so I have to wait few seconds to scan it. (*** I also test on a slow android device :) )
Yes, it works on android as expected.
Waiting your iOS fixes.
Thank you 💯

**Comment by tafelnl** [comment]
Upgrade to the latest version. Should be fixed now!
