### ISSUE TITLE
More info in the Opacity of the WebView section

### ISSUE THREAD

**Issue by Jacobra93** [DutchConcepts/capacitor-barcode-scanner#7]
I do not see the scanner open up when the method is fired. I think this is because the webview is blocking it, because I can see that `background: 'transparent';` is applied but I guess it's not enough. I have tried applying `background: 'transparent';` to other layers, like` ion-app` and `ion-content`, to no avail. 

Any tips or examples of other plugins getting the webview transparent? 

I am trying to use this in an Ionic Capacitor app. The scanner doesn't show up on Android or iOS.

**Comment by Jacobra93** [comment]
I got it to work by adding:

Android, on the body tag:
opacity: 0;
background: none;

iOS, on the html tag:
opacity: 0;

**Comment by tafelnl** [comment]
Thanks for sharing!

**Comment by lewdea** [comment]
> I got it to work by adding:
> 
> Android, on the body tag:
> opacity: 0;
> background: none;
> 
> iOS, on the html tag:
> opacity: 0;

If the root Html tag is set to "opacity: 0", then how can we implement custom UI on camera view?

**Comment by tafelnl** [comment]
@lewdea Fair point. Changing the opacity should not be necessary. Most of the time you should just change the background of one of more divs to none. You can try opening up the app with `chrome://inspect/#devices` for example and inspect every div (top to bottom) to hide their background.

**Comment by Jacobra93** [comment]
@lewdea Good point. Were you able to get it working without using the opacity? I would like to utilize custom UI on the camera view so I guess I'll have to figure something else out.
@tafelnl I tried putting transparent on multiple levels in an Ionic app and nothing seemed to make the camera view show up, but I will try to play around with it some more.

**Comment by tafelnl** [comment]
What you could do to discover what divs are responsible for it, is the following:

Inspect your webapp in your browser. Add some very noticeable background color to `<html>`. Then delete the most upper root div and see if you can see the background color of `<html>`. You do? Nice. Undo the deletion and remove the child of that div. Etc etc. This way you can gradually debug and discover what divs are responsible for overlaying the barcode scanner.

**Comment by lewdea** [comment]
@Jacobra93   I got it working by setting body tag background to transparent too.   There is no need to set every element's style. My app is built with ionic-vue and capacitor.
`BarcodeScanner.hideBackground();
document.body.style.background = "transparent";
result.value = await BarcodeScanner.startScan();`

**Comment by SalahAdDin** [comment]
> What you could do to discover what divs are responsible for it, is the following:
> 
> Inspect your webapp in your browser. Add some very noticeable background color to `<html>`. Then delete the most upper root div and see if you can see the background color of `<html>`. You do? Nice. Undo the deletion and remove the child of that div. Etc etc. This way you can gradually debug and discover what divs are responsible for overlaying the barcode scanner.

I got the `IonTabs` component is hiding it, so, how can i handle it? Also, if we want to create a custom UI, how can we do that?

**Comment by tafelnl** [comment]
You should probably use the native Ionic way of hiding such components (which I do not know anything about unfortunately). You could also try and hide it with JavaScript.

Custom UI can be created in any way you like. An example can be found here: https://github.com/capacitor-community/barcode-scanner/tree/main/examples/scan-area-layout

**Comment by SalahAdDin** [comment]
@tafelnl is there no other way to do this without handling background by ourselves? `cardIo` scanner put the camera over the browser markup as far as i could understand.

**Comment by tafelnl** [comment]
I am not sure what you are willing to accomplish. Your screenvideo looks good to me. Could you elaborate?

**Comment by SalahAdDin** [comment]
Every time i have to reload the app, the scanner screen is showed, it must not be like that; but when i open the scanner, well, i couldn't handle the `IonTabs` component opacity yet.

**Comment by tafelnl** [comment]
I am trying my best to understand @SalahAdDin . But I am still not sure what you mean. What exactly do you mean by reloading? And what exactly happens that you think should not happen?

**Comment by SalahAdDin** [comment]
I made my template like this:
```html
    <div id="scanner-ui" class="scanner-ui">
      <div class="sample-background">
        <!-- this background simulates the camera view -->
      </div>
      <div class="container">
        <div class="barcode-scanner--area--container">
          <div class="relative">
            <p>Kameranızı bir barkoda doğrultun</p>
          </div>
          <div class="square surround-cover">
            <div class="barcode-scanner--area--outer surround-cover">
              <div class="barcode-scanner--area--inner"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="root"></div>
```
`.scanner-ui` has `display: none` by default.

In **React** i get both one and i switch them when it is required.

Thanks.

**Comment by tpharaoh** [comment]
@lewdea I am having a similar issue with vuejs, do you mind posting a snippet?

**Comment by tpharaoh** [comment]
Thanks @lewdea  I tried this based on your idea above and it essentially worked
```
const startScan = async () => {
        document.body.style.opacity="0.2";
      document.body.style.background = "transparent";
      
       BarcodeScanner.hideBackground(); // make background of WebView transparent

      const result = await BarcodeScanner.startScan(); // start scanning and wait for a result

      // if the result has content
      if (result.hasContent) {
          document.body.style.background = "";
          document.body.style.opacity="1";
        console.log(result.content); // log the raw scanned content
      }
    }
```

**Comment by tpharaoh** [comment]
@SalahAdDin did you succeed with this plugin and your design?

Our app has a background, and as other posters that meant I needed the background='transparent' and opacity

I would have liked to have just a portion of the screen with the camera... 

Its OK, client doesn't require it, but I just had a vision :)

**Comment by SalahAdDin** [comment]
We handle it by changing the **body** display attribute while the scanner is on.

**Comment by renatojobal** [comment]
For someone still wondering how to achieve that on an ionic app: 
There should be a file `ionicapp/src/theme/variables.css`. Here you could set the background to transparent on the items `.md body {` and `.ios body {`. For example:
![image](https://user-images.githubusercontent.com/35740463/185966165-fa53be8a-4fd3-4387-a683-826326feaf2d.png)

> The opacity is set by the last two digits on an hexadecimal color. So using 00 at the end will be full transparent.

**Comment by betosimo** [comment]
on ionic, insted of transparent I put a display none on body, like this on global styles:
body.scanner-active {
  --background: transparent;
  --ion-background-color: transparent;
  display: none; 
}
works, but how to get out? theres no cancel button and the slide to left dont work either

**Comment by JanMisker** [comment]
@betosimo with display:none you basically remove/hide your entire app. A cancel button is then also hidden, and swipe gesture probably doesn't work because there is nothing to swipe on. 
What you would have to do is make everything transparent except your cancel/back button.

**Comment by selcukbeyhan** [comment]
> on ionic, insted of transparent I put a display none on body, like this on global styles: body.scanner-active { --background: transparent; --ion-background-color: transparent; display: none; } works, but how to get out? theres no cancel button and the slide to left dont work either

this worked for me too :)

What you can do is:
- if the scan is successful, you set the background back to its original value --> this is what I do
- you can have a timeout to stop the scan if the scan is not successful for some seconds.
